apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: docker
        image: ravishan123/benchtask